### PR TITLE
Update Kali boxes URLs

### PR DESCRIPTION
**Pull request by Sliim**
Add missing boxes
Update URLs from my server to hashicorp.com

Github issues: #160 #407

### CODE REVIEW

**Comment by Sliim** [comment]
Please do not merge this PR, I will change URLs (Hashicorp respond with a 302 to my server)

**Comment by Sliim** [comment]
It's ok for me for reviewing & merging

**Comment by JonTheNiceGuy** [comment]
Bringing this into the new branch. Large merge to follow shortly.

**Comment by JonTheNiceGuy** [comment]
Merged.

**Comment by Sliim** [comment]
Hi @JonTheNiceGuy 

Thanks for the merge. But are you sure it was merged correctly? I don't see my boxes in the gh-pages branch, and the pull request https://github.com/garethr/vagrantboxes-heroku/pull/421/files don't have all my diffs

**Comment by JonTheNiceGuy** [comment]
Oops good spot, I'll pick these up hopefully tomorrow!!

**Comment by JonTheNiceGuy** [comment]
I hope this is right now!

**Comment by Sliim** [comment]
:+1:  Thank you @JonTheNiceGuy  :)

**Pull request closed without merging**
